version: '3.8'

services:
  springboot-app:
    build:
      context: ./backend/generated-springboot
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/dbms
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=test
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
    restart: always
    volumes:
      - ./logs:/app/logs
    depends_on:
      - postgres
      - nginx

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      POSTGRES_DB: dbms
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  nginx:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8089:80"
    restart: always
    depends_on:
      - frontend
    volumes:
      - frontend-output:/usr/share/nginx/html

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    volumes:
      - frontend-output:/app/dist/frontend

volumes:
  pgdata:
  frontend-output:
